docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_DOCKERHUB_AND_HARBOR > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/jinya/jinya-fonts:${CI_COMMIT_TAG}"
      --destination "harbor.ulbricht.casa/jinya/jinya-fonts:latest"
      --destination "jinyacms/jinya-fonts:${CI_COMMIT_TAG}"
      --destination "jinyacms/jinya-fonts:latest"
  rules:
    - if: $CI_COMMIT_TAG
      exists:
        - Dockerfile

build-merge-request:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: build
  script:
    - go vet
    - go build -o jinya-fonts

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

pages:
  stage: deploy
  image: harbor.ulbricht.casa/proxy/library/ruby:latest
  before_script:
    - gem install bundler jekyll
    - bundle update rb-inotify
    - bundle install
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

