version: "3"
services:
  jinya-db:
    container_name: jinya-db
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jinya
      POSTGRES_PASSWORD: jinya
      POSTGRES_DB: jinya
    restart: always