version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily