version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - directory: /angular/frontend
    schedule:
      interval: daily
    package-ecosystem: npm
  - directory: /admin/web
    schedule:
      interval: daily
    package-ecosystem: npm