openapi: 3.0.3
info:
  title: Jinya Fonts
  description: Jinya Fonts
  version: 3.0.0
servers:
  - url: 'https://fonts.jinya.de'
paths:
  /api/font:
    post:
      description: Creates a new webfont
      security:
        - password: [ ]
      requestBody:
        $ref: "./requestBodies/add-webfont.yaml"
      responses:
        201:
          description: Created new font
          content:
            application/json:
              schema:
                $ref: "./entities/webfont.yaml"
    get:
      description: Gets all fonts
      operationId: get_all_fonts
      responses:
        404:
          description: No fonts found
          content:
            text/plain:
              example: Not found
              schema:
                description: No fonts found error
        200:
          description: A list with all fonts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./entities/webfont.yaml"
  /api/font/{fontName}:
    get:
      description: Gets the given font by name
      responses:
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
        200:
          description: The font with the given name
          content:
            application/json:
              schema:
                $ref: "./entities/webfont.yaml"
    put:
      description: Updates the given font
      security:
        - password: [ ]
      requestBody:
        $ref: "./requestBodies/update-webfont.yaml"
      responses:
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
        204:
          description: Successfully updated font
    delete:
      description: Deletes the given font
      security:
        - password: [ ]
      responses:
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
        204:
          description: Successfully deleted font
    parameters:
      - name: fontName
        required: true
        in: path
        schema:
          type: string
  /api/font/{fontName}/file:
    get:
      description: Gets the files for the given font
      responses:
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
        200:
          description: The font files for given font
          content:
            application/json:
              schema:
                $ref: "./entities/metadata.yaml"
    parameters:
      - name: fontName
        required: true
        in: path
        schema:
          type: string
  /api/font/{fontName}/file/{fontSubset}/{fontWeight}/{fontStyle}:
    post:
      description: Uploads a new font file with the given parameters
      requestBody:
        required: true
        content:
          font/woff2:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: Uploaded font successfully
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
    put:
      description: Replaces the woff2 file of the given font and its parameters
      requestBody:
        required: true
        content:
          font/woff2:
            schema:
              type: string
              format: binary
      responses:
        204:
          description: Uploaded font successfully
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
    delete:
      description: Deletes the woff2 file of the given font and its parameters
      responses:
        204:
          description: Deleted woff2 file successfully
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
    parameters:
      - name: fontName
        required: true
        in: path
        schema:
          type: string
      - name: fontSubset
        required: true
        in: path
        schema:
          type: string
      - name: fontWeight
        required: true
        in: path
        schema:
          type: string
          enum:
            - 100
            - 200
            - 300
            - 400
            - 500
            - 600
            - 700
            - 800
            - 900
      - name: fontStyle
        required: true
        in: path
        schema:
          type: string
          enum:
            - normal
            - italic
  /api/font/{fontName}/designer:
    get:
      description: Gets the designers for the given font
      responses:
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
        200:
          description: The designers for given font
          content:
            application/json:
              schema:
                $ref: "./entities/designer.yaml"
    post:
      description: Adds a new designer to the given font
      security:
        - password: [ ]
      requestBody:
        $ref: "./requestBodies/add-designer.yaml"
      responses:
        201:
          description: Created new font
          content:
            application/json:
              schema:
                $ref: "./entities/designer.yaml"
    parameters:
      - name: fontName
        required: true
        in: path
        schema:
          type: string
  /api/font/{fontName}/designer/{designerName}:
    delete:
      description: Deletes given designer from the given font
      responses:
        204:
          description: Deleted designer successfully
        404:
          description: The font was not found
          content:
            text/plain:
              example: Not found
              schema:
                description: Font not found error
    parameters:
      - name: fontName
        required: true
        in: path
        schema:
          type: string
      - name: designerName
        required: true
        in: path
        schema:
          type: string
components:
  securitySchemes:
    password:
      type: apiKey
      in: header
      name: Authorization